# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fed06bc4f4881d8783945bfc06b3007778c632c1abb160c646706f10d10071ed8dd05ca8254ae77f3e89164db8e502002f717ba4ec5135c7c3288b0dcef5b01

test:
  secret_key_base: 6591f0080049b02a4a4596e6e1703afdcade18db3b554766e36702e34f5d09fc30955cb4baf4721da8c5976fbb664f7de648ecf6aa6d9ebe0997266336410792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
